### ISSUE TITLE
Боковая панель

### ISSUE THREAD

**Issue by MarcusAkoev** [snorkysnark/moon-quote#1]
Создать боковую панель (можно настраивать слева или справа).

В панели по переключателю отображать 
- оглавления с переходом
- цитаты

См картинку как в Acrobat Reader сделано.

![image](https://user-images.githubusercontent.com/14274890/188845666-7ce5edb1-fcfe-44f7-b231-fc2ed250f240.png)

**Comment by snorkysnark** [comment]
Добавил такую панель (переключать сторону можно правым кликом по краю экрана).
![2022-09-08_19-11](https://user-images.githubusercontent.com/36006338/189184752-ee159f4a-1ea7-498b-8abb-c1550b86e3e7.png)

**Comment by snorkysnark** [comment]
Можно еще сделать панель для spine - т.е. реальный список документов, хранящихся в epub (обычно их больше, чем глав).

Или совместить:
- Глава 1
    - 1.xhtml
    - 2.xhtml
- ...
