### ISSUE TITLE
Экспорт оглавления, цитат и комментариев  в markdown

### ISSUE THREAD

**Issue by MarcusAkoev** [snorkysnark/moon-quote#2]
Добавить функцию по которой экспортируется 
оглавление с ссылками на разделы.
цитаты и комментариев  с ссылками на место в книге

Желательно иметь возмодность настраивать формат экспорта. Как вариант xslt или слепить чтото свое типа такого.
https://github.com/citation-style-language

Оптимальней xslt 

В формате markdown

**Comment by snorkysnark** [comment]
Сделал базовый экспорт в markdown.
Но, пожалуй, числовые id аннотаций - не лучший вариант.
Скажем, если использовать в качестве id сам EpubCFI (позицию в книге), надо проверять, есть ли такая аннотация в базе - и либо показывать просто выделение (если нет), либо выделение с цветом/комментариями (если есть)?

А для id книги, например, uuid?

**Comment by snorkysnark** [comment]
Насчет xslt не совсем понял: ты имеешь в виду экспорт в xml, а потом преобразование в другой формат сторонней программой?

**Comment by snorkysnark** [comment]
билд: https://github.com/snorkysnark/moon-quote/releases/tag/app-v0.1.2

**Comment by MarcusAkoev** [comment]
Сперва показываем все оглавление

# Section 1
делаем ссылку на место в оглавлении.

по поводу UUID книги наверно да пока так.

**Comment by MarcusAkoev** [comment]
> Насчет xslt не совсем понял: какой формат в итоге должен получаться?
> В markdown же никаких стилей нет

Смотрим пример ниже. Делаешь xml с информацией об оглавлении и пометках (по сути это и есть обменный формат цитат).

делаешь к нему XSL который генерирует текст который и есть маркдаун 

<?xml version="1.0" encoding="windows-1251"?>
<xsl:stylesheet version='1.0'
xmlns:xsl='http://www.w3.org/1999/XSL/Transform'
xmlns:cto="http://www.elsevier.com/xml/cto/dtd"
xmlns:xocs="http://www.elsevier.com/xml/xocs/dtd">
<xsl:output method="text"  encoding="windows-1251"/>
<xsl:template match="/">

  <xsl:apply-templates select="//cto:unique-author"/>
</xsl:template>

<xsl:template match="cto:unique-author">
  <xsl:value-of select="//xocs:eid"/><xsl:text>&#009;</xsl:text><xsl:value-of select="./cto:auth-indexed-name"/>
  <xsl:text>&#013;</xsl:text>

</xsl:template>

</xsl:stylesheet>

**Comment by MarcusAkoev** [comment]
Я думаю оптимальна следующая структура
все пункты заголовков пронумеровать, можно обычным счетчиком.
В цитатах ссылаться на id секции где лежит цитата


<toc>
    <chapter href="..." id=""></chapter>
    <chapter href="..."  id=""></chapter>
    <chapter href="..." id="">
        <chapter href="..." id=""></chapter>
        <chapter href="..."  id=""></chapter>
    </chapter>
    <chapter href="..."  id=""></chapter>
</toc>

<spine>
    <section href="..." refid=""></section>
    <section href="..." refid=""></section>
    <section href="..." refid=""></section>
    <section href="..."  refid=""></section>
    <section href="..."  refid=""></section>
</spine>

**Comment by snorkysnark** [comment]
Можно не вводить новый атрибут, просто `parentHref=""`

**Comment by MarcusAkoev** [comment]
> Можно не вводить новый атрибут, просто `parentHref=""`

давай так попробуем

**Comment by MarcusAkoev** [comment]
Нужно добавить название epub (title) в экспорт

msxsl rez.xml moon-quote2md.xsl  >rez.md

Добавил файл с примером форматирования
moon-quote2md.xsl

**Comment by snorkysnark** [comment]
Сделано пока скриптами на js, с live-reloading (можешь редактировать и сразу видеть изменения).
Пока остается ограничение, что скрипт из одного файла и не имеет доступа к файловой системе (можно попытаться обойти через localhost-сервер)
