### ISSUE TITLE
Листать стрелками

### ISSUE THREAD

**Issue by MarcusAkoev** [snorkysnark/moon-quote#3]
добавить настраиваемые клавиши для листания

стрелки лево право - листаем на один экран назад, вперед
pgup pgdown тоже самое
стрелки вверх низ- листаем на одну показываемую строчку (лучше настраивать)
кнопки home  end - начало конец главы из оглавления
кнопки ctrl+home  ctrl+end - начало конец книги

**Comment by snorkysnark** [comment]
Ага, надо понять, как перебить ивенты в iframe, который читалка создает. Чтобы он не листал 2 раза

**Comment by snorkysnark** [comment]
Итого:
- Пришлось отключить полосу прокрутки (т.к. не вышло даже через preventDefault запретить событие скроллинга) и сделать свою прокрутку. Так что нужен какой-то отдельный индикатор позиции в главе
- Из-за бага в epubjs, когда пытаешься вернуться в предыдущую главу, он перескакивает не в ее конец, а в середину - тоже придется разбираться

**Comment by snorkysnark** [comment]
Хм, оказывается, глава может ссылаться не только на секцию, но и на заголовок внутри секции :/
Давай end будет переходить просто к следующей главе - это проще, чем перескакивать "сверху от заголовка"

**Comment by snorkysnark** [comment]
Пока сделал такое управление:
- Left/PageUp - на экран назад
- Right/PageDown - на экран вперед
- Ctrl + Left/PageUp - предыдущая глава
- Ctrl + Right/PageDown - следующая глава
- Home - в начало текущей главы
- Ctrl + Home - в начало книги
- Ctrl + End - в конец книги

Как определить, где "конец главы", не совсем понятно, т.к. глава - это ссылка на заголовок
