### ISSUE TITLE
Виды аннотаций

### ISSUE THREAD

**Issue by MarcusAkoev** [snorkysnark/moon-quote#8]
- выделении цветом
- комментарии к выделенным цветом цитатам
- заметка, привязанная к любому месту в тексте текстовая заметка. Обозначается значком

**Comment by snorkysnark** [comment]
А "заметка в любом месте" - это просто по координатам x, y?
Или привязанная к символам в тексте?

**Comment by MarcusAkoev** [comment]
> А "заметка в любом месте" - это просто по координатам x, y? Или привязанная к символам в тексте?

к символам текста

**Comment by snorkysnark** [comment]
см. прогресс здесь: #10
